# broker:
#   host: 'broker.hivemq.com'             # [localhost] IP address or hostname of the machine running the MQTT broker
#   port: 1883             # [1883] port the MQTT broker is listening on
#   # user:              # username used for authenticating to the broker (if empty, will try to connect anonymously)
#   # pass:              # password used for authenticating to the broker
#   # tls:
#     # enabled:           # [false] whether to connect via SSL/TLS
#     # ca_certificate:    # [/etc/ssl/certs/ca-certificates.crt] CA certificate file trusted by client (relative to ROS_HOME)

# # object List:
# # ika_acdc_22/objectList_a
# # ika_acdc_22/objectList_b
# bridge:
#   # ros2mqtt:              # Array specifying which ROS topics to map to which MQTT topics
#   #   - ros_topic:         # ROS topic whose messages are transformed to MQTT messages
#   #     mqtt_topic:        # MQTT topic on which the corresponding ROS messages are sent to the broker
#   #     primitive:         # [false] whether to publish as primitive message
#   #     inject_timestamp:  # [false] whether to attach a timestamp to a ROS2MQTT payload (for latency computation on receiver side)
#   #     advanced:
#   #       ros:
#   #         queue_size:    # [1] ROS subscriber queue size
#   #       mqtt:
#   #         qos:           # [0] MQTT QoS value
#   #         retained:      # [false] whether to retain MQTT message
#   mqtt2ros:              # Array specifying which MQTT topics to map to which ROS topics
#     - mqtt_topic: ika_acdc_22         # MQTT topic on which messages are received from the broker
#       ros_topic: ika_acdc_22/objectList_a        # ROS topic on which corresponding MQTT messages are published
#       # primitive:         # [false] whether to publish as primitive message (if coming from non-ROS MQTT client)
#       # advanced:
#         # mqtt:
#           # qos:           # [0] MQTT QoS value
#         # ros:
#           # queue_size:    # [1] ROS publisher queue size
#           # latched:       # [false] whether to latch ROS message


broker:
  host: broker.hivemq.com
  port: 1883

bridge:
  mqtt2ros:
    # Station A
    - mqtt_topic: ika_acdc_22/objectList_a
      ros_topic: /topicA
    # Station B
    - mqtt_topic: ika_acdc_22/objectList_b
      ros_topic: /topicB
    # Ground Truth
    - mqtt_topic: ika_acdc_22/objectList_gt
      ros_topic: /topicGT
    # SPATEM
    - mqtt_topic: ika_acdc_22/SPATEM
      ros_topic: /SPATEM
    # MAPEM
    - mqtt_topic: ika_acdc_22/MAPEM
      ros_topic: /MAPEM